### ISSUE TITLE
必须全局安装么？

### ISSUE THREAD

**Issue by Mister-Hope** [wechat-miniprogram/miniprogram-slim#3]
执行 yarn add miniprogram-slim:

```
error Z:\miniprogram\inNENU\node_modules\pngquant-bin: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments:
Directory: Z:\miniprogram\inNENU\node_modules\pngquant-bin
Output:
‼ getaddrinfo ENOENT raw.githubusercontent.com
  ‼ pngquant pre-build test failed
  i compiling from source
  × Error: pngquant failed to build, make sure that libpng-dev is installed
```

**Comment by CruxCv** [comment]
> 执行 yarn add miniprogram-slim:
> 
> ```
> error Z:\miniprogram\inNENU\node_modules\pngquant-bin: Command failed.
> Exit code: 1
> Command: node lib/install.js
> Arguments:
> Directory: Z:\miniprogram\inNENU\node_modules\pngquant-bin
> Output:
> ‼ getaddrinfo ENOENT raw.githubusercontent.com
>   ‼ pngquant pre-build test failed
>   i compiling from source
>   × Error: pngquant failed to build, make sure that libpng-dev is installed
> ```

是的亲，但是还会报错哦~

**Comment by ghost** [comment]
> > 执行 yarn add miniprogram-slim:
> > ```
> > error Z:\miniprogram\inNENU\node_modules\pngquant-bin: Command failed.
> > Exit code: 1
> > Command: node lib/install.js
> > Arguments:
> > Directory: Z:\miniprogram\inNENU\node_modules\pngquant-bin
> > Output:
> > ‼ getaddrinfo ENOENT raw.githubusercontent.com
> >   ‼ pngquant pre-build test failed
> >   i compiling from source
> >   × Error: pngquant failed to build, make sure that libpng-dev is installed
> > ```
> 
> 是的亲，但是还会报错哦~

请问这个问题有解决方案吗？

**Comment by lichenglong-blog** [comment]
> > > 执行 yarn add miniprogram-slim:
> > > ```
> > > error Z:\miniprogram\inNENU\node_modules\pngquant-bin: Command failed.
> > > Exit code: 1
> > > Command: node lib/install.js
> > > Arguments:
> > > Directory: Z:\miniprogram\inNENU\node_modules\pngquant-bin
> > > Output:
> > > ‼ getaddrinfo ENOENT raw.githubusercontent.com
> > >   ‼ pngquant pre-build test failed
> > >   i compiling from source
> > >   × Error: pngquant failed to build, make sure that libpng-dev is installed
> > > ```
> > 
> > 
> > 是的亲，但是还会报错哦~
> 
> 请问这个问题有解决方案吗？

cnpm
